export { LoginComponent } from './login/login.component';
export { LeftMenuComponent } from './left-menu/left-menu.component';
export { HeaderComponent } from './header/header.component';
export { LoginHeaderComponent } from './login-header/login-header.component';
export { LoginFooterComponent } from './login-footer/login-footer.component';
export { FooterComponent } from './footer/footer.component';
export { DashboardComponent } from './dashboard/dashboard.component';
export { PageSizeRenderComponent } from './common/page-size-render/page-size-render.component';
export { PaginationRenderComponent } from './common/pagination-render/pagination-render.component';
export { SearchRenderComponent } from './common/search-render/search-render.component';
export { ConfirmDialogComponent } from './common/confirm-dialog/confirm-dialog.component';
export { DeleteDialogComponent } from './common/delete-dialog/delete-dialog.component';
export { MessageDialogComponent } from './common/message-dialog/message-dialog.component';
export { DeviceListComponent } from './device/device-list/device-list.component';
export { ResetpasswordComponent } from './resetpassword/resetpassword.component';
export { ExtendMeetingComponent } from './common/extend-meeting/extend-meeting.component';
export { SettingsComponent } from './settings/settings.component';
export { FlashMessageComponent } from './flash-message/flash-message.component';
export { DeviceAddComponent } from './device/device-add/device-add.component';
export { UserListComponent } from './user/user-list/user-list.component';
export { UserAddComponent } from './user/user-add/user-add.component';
export { RolesListComponent } from './roles/roles-list/roles-list.component';
export { RolesAddComponent } from './roles/roles-add/roles-add.component';
export { ElevatorDetailsComponent } from './elevator/elevator-details/elevator-details.component';
export { MyProfileComponent } from './my-profile/my-profile.component';
export { ChangePasswordComponent } from './change-password/change-password.component';
export { HomeComponent } from './home/home.component';
export { RegisterComponent } from './subscribe/register/register.component';
export { PaymentComponent } from './subscribe/payment/payment.component';
export { PurchasePlanComponent } from './subscribe/purchase-plan/purchase-plan.component';
// export { SitelayoutComponent } from './sitelayout/sitelayout.component';
//export { BreadcrumbComponent } from './breadcrumb/breadcrumb.component';
export {CallbackComponent } from './callback/callback.component';
export { BuildingListComponent } from './building/building-list/building-list.component';
export { BuildingAddComponent } from './building/building-add/building-add.component';
export { BuildingDetailsComponent } from './building/building-details/building-details.component';
export { ScheduledMaintenanceListComponent } from './scheduled-maintenance/scheduled-maintenance-list/scheduled-maintenance-list.component';
export { ScheduledMaintenanceAddComponent } from './scheduled-maintenance/scheduled-maintenance-add/scheduled-maintenance-add.component';
export { AdminUserListComponent } from './admin/admin-user/admin-user-list/admin-user-list.component';
export { AdminUserAddComponent } from './admin/admin-user/admin-user-add/admin-user-add.component';

export { AdminLoginComponent } from './admin/admin-login/admin-login.component';
export { AdminDashboardComponent } from './admin/admin-dashboard/admin-dashboard.component';
export { SubscribersListComponent } from './admin/subscribers/subscribers-list.component';
export { HardwareListComponent } from './admin/hardware-kit/hardware-kit-list/hardware-kit-list.component';
export { HardwareAddComponent } from './admin/hardware-kit/hardware-kit-add/hardware-kit-add.component';
export { SubscriberDetailComponent } from './admin/subscribers/subscriber-detail/subscriber-detail.component';
export { BulkuploadAddComponent } from './admin/bulk-upload/bulk-upload-add/bulk-upload-add.component';
export { NotificationListComponent } from './notification/notification-list/notification-list.component';
export { NotificationAddComponent } from './notification/notification-add/notification-add.component';
export { AdminNotificationListComponent } from './admin/notification/admin-notification-list/admin-notification-list.component';
export { AdminNotificationAddComponent } from './admin/notification/admin-notification-add/admin-notification-add.component';

export { ElevatorListComponent } from './elevator/elevator-list/elevator-list.component';
export { ElevatorAddComponent } from './elevator/elevator-add/elevator-add.component';
export { AlertsComponent } from './alerts/alerts.component';

/*Dynamic Dashboard Start*/
export { DynamicDashboardComponent } from './dynamic-dashboard/dynamic-dashboard/dynamic-dashboard.component';
export { WidgetCounterAComponent } from './dynamic-dashboard/child-components/widget-counter-a/widget-counter-a.component';
export { WidgetCounterBComponent } from './dynamic-dashboard/child-components/widget-counter-b/widget-counter-b.component';
export { WidgetCounterCComponent } from './dynamic-dashboard/child-components/widget-counter-c/widget-counter-c.component';
export { WidgetCounterDComponent } from './dynamic-dashboard/child-components/widget-counter-d/widget-counter-d.component';
export { WidgetCounterEComponent } from './dynamic-dashboard/child-components/widget-counter-e/widget-counter-e.component';
export { WidgetCounterFComponent } from './dynamic-dashboard/child-components/widget-counter-f/widget-counter-f.component';
export { WidgetAlertAComponent } from './dynamic-dashboard/child-components/widget-alert-a/widget-alert-a.component';
export { WidgetAlertBComponent } from './dynamic-dashboard/child-components/widget-alert-b/widget-alert-b.component';
export { WidgetChartAComponent } from './dynamic-dashboard/child-components/widget-chart-a/widget-chart-a.component';
export { WidgetChartBComponent } from './dynamic-dashboard/child-components/widget-chart-b/widget-chart-b.component';
export { SizeDetectorComponent } from './dynamic-dashboard/size-detector/size-detector.component';
/*Dynamic Dashboard End*/
